### ISSUE TITLE
Transferable Detection?

### ISSUE THREAD

**Issue by ironhacker** [MattiasBuelens/remote-web-streams#24]
Are transferables detected or is there a configuration option to enable efficient zero-copy transfers?  e.g. `worker.postMessage(uInt8Array, [uInt8Array.buffer])`

**Comment by MattiasBuelens** [comment]
Both `new RemoteWritableStream()` and `fromWritablePort()` take [an optional `options` object](https://github.com/MattiasBuelens/remote-web-streams/blob/v0.1.0/src/writable.ts#L6-L8) which can have a `transferChunk` callback. It receives a `chunk`, and it can return a transfer list that will be passed as second parameter to `postMessage()`. (It looks like I didn't write any documentation about this yet, sorry about that! 😅)

```javascript
const { writable, readablePort } = new RemoteWebStreams.RemoteWritableStream({
  transferChunk(chunk) {
    if (chunk instanceof Uint8Array) {
      return [chunk.buffer];
    }
    return [];
  }
});
worker.postMessage({ readablePort }, [readablePort]);
const writer = writable.getWriter();
writer.write(new Uint8Array([1, 2, 3, 4])); // will be transferred to other end
```

**Comment by ironhacker** [comment]
Thank you. This was perfect and the library is exactly what I needed.
